version: "3.8"
services:
  app:
    build: .
    container_name: app
    command: flask run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    restart_policy:
      condition: any
